name = "freemail"
main = "src/server.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "freemail-db"
database_id = "replace-with-your-d1-database-id"

[vars]
# FORWARD_RULES = "[{\"prefix\":\"vip\",\"email\":\"a@example.com\"},{\"prefix\":\"*\",\"email\":\"fallback@example.com\"}]"

[assets]
directory = "public"
binding = "ASSETS"

[[r2_buckets]]
binding = "MAIL_EML"
bucket_name = "replace-with-your-r2-bucket-name"

# [observability.logs]
# enabled = true
